def exception_error(error):
  exception = {}
  exception['error'] = error

  return exception